apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
	app: python
spec:
  replicas: 3
  selector:
	matchLabels:
  	app: python
  template:
	metadata:
  	labels:
    	app: python
	spec:
  	containers:
  	- name: flask-app
    	image: lastyearproject/dockerapps:flask-image
    	ports:
    	- containerPort: 5000
